#!/usr/bin/env bash
php bin/archive.php

if [ $? -eq 0 ]; then
    echo "Archive success"
else
    echo "Archive failed"
    exit 1
fi

autocorrect --fix docs/t/index.md
autocorrect --fix docs/daily.md

git add *
git add .gitignore
git commit -m "docs: add post `date "+%Y-%m-%d"`"
git push