# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: node bin/gen-sidebar.js > docs/.vuepress/sidebar.js
    - run: yarn docs:build
    - run: cp CNAME docs/.vuepress/dist
    - name: commit push
      run: |
        rm -rf .git
        cd docs/.vuepress/dist
        git config --global init.defaultBranch gh-pages
        git init
        git branch -m gh-pages
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git config --global user.name 'sntfly'
        git config --global user.email 'yang623601391@gmail.com'
        git commit -am "auto build"
        git push --set-upstream origin gh-pages -f
